#include <iostream>
/*
Counting steps for a hiker through valleys and mountains. 
0 is sea level so for the hiker to calculate how many valleys (which is what we care about) 
check for every time the current step is 0 and the current char in string is 'U' (for up).
That would denote the leaving of a valley so no need to calculate anything else.
*/
#if 1
int countingValleys(int n, std::string s)
{
    int step = 0;
    int numOfValleys = 0;
    for (int i = 0; i < s.size(); i++)
    {
        if (s[i] == 'U')
        {
            step++;
        }
        else 
        {
            step--;
        }
        std::cout << step << std::endl;
        
        if (step == 0 && s[i] == 'U')
        {
            numOfValleys++;
        }
    }
    return numOfValleys;
}
#endif

int main() {
	
    int n = 8;
    int n2 = 1000000;
    std::string s = "UDDDUDUU";
    std::string s2 = "UUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUDDDDDUUUUUD";

    std::cout << "\n\nNum of valleys: " << countingValleys(n2, s2);

	return 0;

}